# Generated by Django 6.1 on 2026-08-14 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The gratitude reflection and notes for the day')),
                ('date', models.DateField(help_text='The date of this gratitude entry (one entry per user per date)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who wrote this gratitude journal entry', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gratitude Entry',
                'verbose_name_plural': 'Gratitude Entries',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'date'), name='unique_owner_date_entry')],
            },
        ),
    ]
